apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: todo-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spring-todo-deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 30